CREATE TABLE IF NOT EXISTS [config] (
	[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
	[type] NVARCHAR(256)  NULL,
	[key] NVARCHAR(256)  NULL,
	[value] NVARCHAR(256)  NULL,
	[des] NVARCHAR(256)  NULL
)